/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    leads: Lead;
    solutions: Solution;
    projects: Project;
    products: Product;
    pages: Page;
    testimonials: Testimonial;
    faqs: Faq;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    solutions: SolutionsSelect<false> | SolutionsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    site: Site;
    home: Home;
    contact: Contact;
  };
  globalsSelect: {
    site: SiteSelect<false> | SiteSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Public form, quiz, and franchise submissions.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  phone?: string | null;
  email?: string | null;
  city?: string | null;
  source?: string | null;
  propertyType?: string | null;
  message?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions".
 */
export interface Solution {
  id: number;
  title: string;
  description: string;
  image: string;
  alt?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  description: string;
  image: string;
  alt?: string | null;
  meta?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Catalogue shown on the home page. No separate product routes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * Short spec line, e.g. 24V / 250–400 watts
   */
  spec?: string | null;
  description: string;
  category: 'pv' | 'inverter' | 'rooftop' | 'structure' | 'bos' | 'heater';
  image?: string | null;
  alt?: string | null;
  cta?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * About, services and other site pages. Header and footer links use the slug.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  badge?: string | null;
  description?: string | null;
  sections?:
    | {
        title: string;
        description?: string | null;
        href?: string | null;
        cta?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  quote: string;
  image: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'solutions';
        value: number | Solution;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  city?: T;
  source?: T;
  propertyType?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions_select".
 */
export interface SolutionsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
  alt?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
  alt?: T;
  meta?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  spec?: T;
  description?: T;
  category?: T;
  image?: T;
  alt?: T;
  cta?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  badge?: T;
  description?: T;
  sections?:
    | T
    | {
        title?: T;
        description?: T;
        href?: T;
        cta?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  quote?: T;
  image?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site".
 */
export interface Site {
  id: number;
  name: string;
  shortName?: string | null;
  tagline?: string | null;
  email?: string | null;
  consultEmail?: string | null;
  phone?: string | null;
  phoneHref?: string | null;
  whatsappHref?: string | null;
  address?: string | null;
  mapsQuery?: string | null;
  footerHeadline?: string | null;
  footerDescription?: string | null;
  footerCta?: string | null;
  certifications?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  offices?:
    | {
        city: string;
        address: string;
        id?: string | null;
      }[]
    | null;
  navLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footerLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  headerCta?: {
    label?: string | null;
    href?: string | null;
  };
  socials?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  heroSlides?:
    | {
        badge?: string | null;
        badgeSuffix?: string | null;
        title: string;
        description?: string | null;
        cta?: string | null;
        ctaHref?: string | null;
        secondaryCta?: string | null;
        secondaryHref?: string | null;
        skyImage?: string | null;
        houseImage?: string | null;
        houseAlt?: string | null;
        id?: string | null;
      }[]
    | null;
  trust?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  brandsIntro?: {
    badge?: string | null;
    title?: string | null;
    description?: string | null;
  };
  brands?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  about?: {
    badge?: string | null;
    title?: string | null;
    description?: string | null;
    cta?: string | null;
    ctaHref?: string | null;
    image?: string | null;
    imageAlt?: string | null;
    cardDate?: string | null;
    cardTitle?: string | null;
    cardDescription?: string | null;
  };
  stats?:
    | {
        value: number;
        suffix?: string | null;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  solutionsIntro?: {
    badge?: string | null;
    title?: string | null;
    description?: string | null;
  };
  solutions?:
    | {
        title: string;
        description: string;
        image: string;
        alt?: string | null;
        cta?: string | null;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  servicesIntro?: {
    badge?: string | null;
    title?: string | null;
    description?: string | null;
  };
  services?:
    | {
        title: string;
        description: string;
        image: string;
        alt?: string | null;
        cta?: string | null;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  benefitsIntro?: {
    badge?: string | null;
    title?: string | null;
    description?: string | null;
  };
  benefits?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  benefitsImage?: string | null;
  benefitsImageAlt?: string | null;
  productsIntro?: {
    badge?: string | null;
    title?: string | null;
    description?: string | null;
  };
  projectsIntro?: {
    badge?: string | null;
    title?: string | null;
    description?: string | null;
  };
  howItWorks?: {
    badge?: string | null;
    title?: string | null;
    description?: string | null;
  };
  steps?:
    | {
        number: string;
        title: string;
        points?: string | null;
        id?: string | null;
      }[]
    | null;
  quiz?: {
    badge?: string | null;
    title?: string | null;
    description?: string | null;
    questions?:
      | {
          question: string;
          options?: string | null;
          placeholder?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  testimonialsIntro?: {
    badge?: string | null;
    title?: string | null;
    description?: string | null;
  };
  faqIntro?: {
    badge?: string | null;
    title?: string | null;
    description?: string | null;
    helpTitle?: string | null;
    helpDescription?: string | null;
  };
  locationsIntro?: {
    badge?: string | null;
    title?: string | null;
    description?: string | null;
  };
  lead?: {
    badge?: string | null;
    title?: string | null;
    description?: string | null;
    cta?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  badge?: string | null;
  title?: string | null;
  description?: string | null;
  franchiseBadge?: string | null;
  franchiseTitle?: string | null;
  franchiseDescription?: string | null;
  cards?:
    | {
        title: string;
        description?: string | null;
        href?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  propertyTypes?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_select".
 */
export interface SiteSelect<T extends boolean = true> {
  name?: T;
  shortName?: T;
  tagline?: T;
  email?: T;
  consultEmail?: T;
  phone?: T;
  phoneHref?: T;
  whatsappHref?: T;
  address?: T;
  mapsQuery?: T;
  footerHeadline?: T;
  footerDescription?: T;
  footerCta?: T;
  certifications?:
    | T
    | {
        label?: T;
        id?: T;
      };
  offices?:
    | T
    | {
        city?: T;
        address?: T;
        id?: T;
      };
  navLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  headerCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  socials?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  heroSlides?:
    | T
    | {
        badge?: T;
        badgeSuffix?: T;
        title?: T;
        description?: T;
        cta?: T;
        ctaHref?: T;
        secondaryCta?: T;
        secondaryHref?: T;
        skyImage?: T;
        houseImage?: T;
        houseAlt?: T;
        id?: T;
      };
  trust?:
    | T
    | {
        label?: T;
        id?: T;
      };
  brandsIntro?:
    | T
    | {
        badge?: T;
        title?: T;
        description?: T;
      };
  brands?:
    | T
    | {
        name?: T;
        id?: T;
      };
  about?:
    | T
    | {
        badge?: T;
        title?: T;
        description?: T;
        cta?: T;
        ctaHref?: T;
        image?: T;
        imageAlt?: T;
        cardDate?: T;
        cardTitle?: T;
        cardDescription?: T;
      };
  stats?:
    | T
    | {
        value?: T;
        suffix?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  solutionsIntro?:
    | T
    | {
        badge?: T;
        title?: T;
        description?: T;
      };
  solutions?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        alt?: T;
        cta?: T;
        href?: T;
        id?: T;
      };
  servicesIntro?:
    | T
    | {
        badge?: T;
        title?: T;
        description?: T;
      };
  services?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        alt?: T;
        cta?: T;
        href?: T;
        id?: T;
      };
  benefitsIntro?:
    | T
    | {
        badge?: T;
        title?: T;
        description?: T;
      };
  benefits?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  benefitsImage?: T;
  benefitsImageAlt?: T;
  productsIntro?:
    | T
    | {
        badge?: T;
        title?: T;
        description?: T;
      };
  projectsIntro?:
    | T
    | {
        badge?: T;
        title?: T;
        description?: T;
      };
  howItWorks?:
    | T
    | {
        badge?: T;
        title?: T;
        description?: T;
      };
  steps?:
    | T
    | {
        number?: T;
        title?: T;
        points?: T;
        id?: T;
      };
  quiz?:
    | T
    | {
        badge?: T;
        title?: T;
        description?: T;
        questions?:
          | T
          | {
              question?: T;
              options?: T;
              placeholder?: T;
              id?: T;
            };
      };
  testimonialsIntro?:
    | T
    | {
        badge?: T;
        title?: T;
        description?: T;
      };
  faqIntro?:
    | T
    | {
        badge?: T;
        title?: T;
        description?: T;
        helpTitle?: T;
        helpDescription?: T;
      };
  locationsIntro?:
    | T
    | {
        badge?: T;
        title?: T;
        description?: T;
      };
  lead?:
    | T
    | {
        badge?: T;
        title?: T;
        description?: T;
        cta?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  badge?: T;
  title?: T;
  description?: T;
  franchiseBadge?: T;
  franchiseTitle?: T;
  franchiseDescription?: T;
  cards?:
    | T
    | {
        title?: T;
        description?: T;
        href?: T;
        label?: T;
        id?: T;
      };
  propertyTypes?:
    | T
    | {
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}